version: '2'
services:
    phb:
        image: e96tech/phabricator
        container_name: phabricator
        environment:
          - SERVICE_HOST=phabricator.docker
          - SQL_HOST=localhost
          - SQL_PORT=3306
          - SQL_USER=root
          - SQL_PASS=mysecret
          - SPRINT_PLUGIN_PATH=/var/www/phabricator/plugins/sprints/src
        volumes:
          - /home/alexander/www/phabricator/plugins:/var/www/phabricator/plugins
        ports:
          - 22:22
          - 80:80
          - 443:443
          - 22280:22280